name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm install
          npm run-script build
        env:
          NEXT_PUBLIC_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_CLIENT_ID }}
          NEXT_PUBLIC_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_CLIENT_SECRET }}
          NEXT_PUBLIC_TEST_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_CLIENT_SECRET }}
          NEXT_PUBLIC_TEST_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_CLIENT_SECRET }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
